### ISSUE TITLE
ProjectionVersion: Allow to define prefix

### ISSUE THREAD

**Issue by Zeeker** [slashdotdash/commanded-ecto-projections#3]
We use commanded in an umbrella application which contains multiple applications, some of them having their own data storage. As such we want to have a separate projection version table for each application making use of CQRS.

Due to the way Ecto allows to define prefixes there seems to be no way to define a prefix for the ProjectionVersion schema. Any idea on how this could be achieved? Maybe via a config option?

**Comment by slashdotdash** [comment]
It's not currently supported, but could be added by extending the config to support a schema. Here's a proposal:

```elixir
defmodule MyProjector do
  use Commanded.Projections.Ecto,
    name: "my-projection",
    schema_prefix: "myapp",
    repo: MyRepo    
```

Another approach would be to add a column to the `projection_versions` table, such as `context` or `application`, and specify the value for each projection. This would allow you to identity which app the projection belongs to within the single table.

```elixir
defmodule MyProjector do
  use Commanded.Projections.Ecto,
    name: "my-projection",
    context: "myapp",
    repo: MyRepo
```

Which option would you choose?

**Comment by Zeeker** [comment]
I prefer the first version.

While the second version has it's merits it would be unclear in which schema the `projection_versions` table belongs, assuming that the usage of the default schema is not an option.

**Comment by Zeeker** [comment]
I can prepare a PR, if you want.

**Comment by slashdotdash** [comment]
Happy to accept a pull request from you. 

Having thought about the changes needed, I think the existing `Commanded.Projections.ProjectionVersion` module will need to be included within the `Commanded.Projections.Ecto` macro to allow the definition of `@schema_prefix`. So each projection has its own definition of the schema module. 

Good luck if you have a go; drop me a message if you get stuck.
